name: Auto Cloud Sync to Roblox

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Aftman Tools
        uses: ok-nick/setup-aftman@v0.4.2

      - name: Build and Push Headless to Roblox Cloud
        run: |
          rojo build --output game.rbxl
          rbxcloud experience publish --filename game.rbxl --place-id 129122438210317 --universe-id 996926968 --version-type published --api-key NDI9F+NB+k6ilKV9GLxI71TTFdL8P8X2ICMBOey8Ugv0BI2NZXlKaGJHY2lPaUpTVXpJMU5pSXNJbXRwWkNJNkluTnBaeTB5TURJeExUQTNMVEV6VkRFNE9qVXhPalE1V2lJc0luUjVjQ0k2SWtwWFZDSjkuZXlKaGRXUWlPaUpTYjJKc2IzaEpiblJsY201aGJDSXNJbWx6Y3lJNklrTnNiM1ZrUVhWMGFHVnVkR2xqWVhScGIyNVRaWEoyYVdObElpd2lZbUZ6WlVGd2FVdGxlU0k2SWs1RVNUbEdLMDVDSzJzMmFXeExWamxIVEhoSk56RlVWRVprVERoUU9GZ3lTVU5OUWs5bGVUaFZaM1l3UWtreVRpSXNJbTkzYm1WeVNXUWlPaUl4T0RZMk1UZzRNVFU0SWl3aVpYaHdJam94Tnprd016WTRNRFV6TENKcFlYUWlPakUzT1RBek5qUTBOVE1zSW01aVppSTZNVGM1TURNMk5EUTFNMzAuWHZMYkpmcThOc3JZMnRTME4xS050TExjNVUxMldZQ2ltS0tFWklCZnZoZ1BTd1lkc2pjNDk4R2g1VDU5V3ZiTUFTNVNqTlcxNWRMeHRiMnlmaUtqWWFtZnZmNFZ3Qi1nbWZSeG5IVGJJa0I0WDhrUnl2T1AzVXdnS0FDY3ZYdHpwLWJlSndOLXF4UnV3cEhQYnl6XzM5QVQxUWtkbnEyZHpLNlZFWGMzWXFLNlhJUjBOSVdxZTdVWnNtQ1R0UGVPSER6Q05mcWlPWEVQSzMwUVRzN2hOeGpVdUJEUWhCOWx1X3V5amZ0VzUwRHBVTEtKTUkxeHZqenNYS2lDcmRwS1FJRDhYRElqSzZFQkFwcUFWTklnV1NZZE5Demc2VVFqc2xtdHpueDVwMk9XQmJpV1R1c0I5Z2I4c2daOGh3c1dhNGhiUURTRmhrWUJVS0FIT2tCdk5n